.\"     Title: a2x
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/11/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "A2X" "1" "09/11/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
a2x \- convert Asciidoc text file to PDF, XHTML, HTML Help, manpage or plain text
.SH "SYNOPSIS"
\fIa2x\fR [OPTIONS] FILE
.sp
.SH "DESCRIPTION"
A DocBook toolchain wrapper script that translates an \fIAsciiDoc\fR text file \fIFILE\fR to PDF, XHTML (single page or chunked), man page, HTML Help or plain text formats. PDF, XHTML, man page and HTML Help formats are are generated using the asciidoc(1)/xsltproc(1)/DocBook XSL Stylesheets toolchain. Plain text is produced by passing asciidoc(1) generated HTML through lynx(1). The htmlhelp format option generates .hhp, .hhc and .html files suitable for compilation to an HTML Help .chm file.
.sp
.SH "OPTIONS"
.PP
\-a, \-\-attribute=ATTRIBUTE
.RS 4
Set
asciidoc(1)
attribute value (shortcut for
\fI\-\-asciidoc\-opts="\-a ATTRIBUTE"\fR
option). This option may be specified more than once.
.RE
.PP
\-\-asciidoc\-opts=ASCIIDOC_OPTS
.RS 4
Additional
asciidoc(1)
options. This option may be specified more than once.
.RE
.PP
\-\-copy
.RS 4
Copy distributed docbook\-xsl CSS stylesheet and the copying of distributed admonition and navigation icons to their respective destinations. Applies to xhtml, chunked, htmlhelp formats. The default behavior is to suppress copying.
.RE
.PP
\-D, \-\-destination\-dir=PATH
.RS 4
Output directory. Defaults to source FILE directory.
.RE
.PP
\-d, \-\-doctype=DOCTYPE
.RS 4
DocBook document type:
\fIarticle\fR,
\fImanpage\fR
or
\fIbook\fR. Default document type is
\fIarticle\fR
unless the format is
\fImanpage\fR
(in which case it defaults to
\fImanpage\fR).
.RE
.PP
\-f, \-\-format=FORMAT
.RS 4
Output format: chunked, htmlhelp, manpage, pdf, text or xhtml.
.RE
.PP
\-h, \-\-help
.RS 4
Print command\-line syntax and program options to stdout.
.RE
.PP
\-\-icons
.RS 4
Use admonition or navigation icon images in output documents. The default behavior is to use text in place of icons.
.RE
.PP
\-\-icons\-dir=PATH
.RS 4
A path (relative to destination HTML files) containing admonition and navigation icons. Defaults to ./images/icons/. Applies to xhtml, chunked, htmlhelp formats.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Don't do anything just print what would have been done.
.RE
.PP
\-s, \-\-skip\-asciidoc
.RS 4
Skip asciidoc execution. This is useful for converting DocBook XML files not derived from
\fIAsciiDoc\fR
sources. Ignored if \-\-format=text.
.RE
.PP
\-\-stylesheet=PATH
.RS 4
A path (relative to destination HTML files) specifying the docbook\-xsl CSS stylesheet file. Defaults to ./docbook\-xsl.css. Applies to xhtml, chunked, htmlhelp formats.
.RE
.PP
\-v, \-\-verbose
.RS 4
Print operational details to stderr. A second \-v option applies the verbose option to toolchain commands.
.RE
.PP
\-\-version
.RS 4
Print program version to stdout.
.RE
.PP
\-\-xsltproc\-opts=XSLTPROC_OPTS
.RS 4
Additional xsltproc(1) options. This option may be specified more than once.
.RE
.SH "OUTPUT FILES"
Output files are written to the directory specified by the \fI\-\-destination\-dir\fR option. If no \fI\-\-destination\-dir\fR option is set output files are written to the source FILE directory.
.sp
Output files have the same name as the source FILE but with an appropriate file name extension: .html for xhtml; .hhp for htmlhelp; .pdf for pdf; .text for text. By convention manpages have no .man extension (man page section number only). Chunked HTML directory names have a .chunked extension; chunked HTML Help directory names have a .htmlhelp extension.
.sp
Same named existing files are overwritten.
.sp
Intermediate output files are written to the source FILE directory and are not automatically deleted.
.sp
Intermediate DocBook XML files generated by \fIAsciiDoc\fR are only regenerated if out of date with respect to the \fIAsciiDoc\fR source FILE.
.sp
In addition to generating HTML files the xhtml, chunked and htmlhelp formats copy the DocBook XSL stylesheet plus admonition and navigation icons distributed with \fIAsciiDoc\fR to their respective destination locations. Existing stylesheets and icons are only copied if they are newer than the destination files or if the destination files are missing.
.sp
The xhtml format generates a single XHTML output page. The chunked format writes multiple per\-section HTML pages to a chunked directory in the destination directory. The chunked directory has the same name as the source FILE name plus a .chunked extension.
.sp
.SH "EXAMPLES"
.PP
a2x \-f pdf \-\-icons doc/quickstart.txt
.RS 4
Generates doc/quickstart.pdf with admonition icons.
.RE
.PP
a2x \-f chunked \-D ../webpages guide.txt
.RS 4
Creates chunked directory
\&../webpages/guide.chunked
containing chunked HTML files. Also copies
docbook\-xsl.css
stylesheet to the
\&../webpages/guide.chunked
directory plus admonition and navigation icons to the
\&../webpages/guide.chunked/images/icons
directory.
.RE
.SH "REQUISITES"
This script runs under the bash(1) shell and requires the following programs (which may or may not be prepackaged with your Linux distribution):
.sp
.PP
Asciidoc
.RS 4
http://www.methods.co.nz/asciidoc/
.RE
.PP
xsltproc
.RS 4
http://xmlsoft.org/XSLT/
.RE
.PP
DocBook XSL Stylesheets
.RS 4
http://docbook.sourceforge.net/projects/xsl/
.RE
.PP
FOP (for PDF file generation)
.RS 4
http://xmlgraphics.apache.org/fop/
.RE
.PP
Lynx (for text file generation)
.RS 4
http://lynx.isc.org/
.RE
This version of a2x(1) has been tested on Ubuntu Linux 5.0.4 with the following toolchain components:
.sp
.RS 4
\h'-04'\(bu\h'+03'bash 3.00.16.
.RE
.RS 4
\h'-04'\(bu\h'+03'DocBook XSL Stylesheets 1.72.0 (with
\fIAsciiDoc\fR
drivers and patches).
.RE
.RS 4
\h'-04'\(bu\h'+03'xsltproc (libxml 20627, libxslt 10120 and libexslt 813).
.RE
.RS 4
\h'-04'\(bu\h'+03'FOP 0.20.5.
.RE
.RS 4
\h'-04'\(bu\h'+03'lynx 2.8.5rel.1.
.RE
.SH "BUGS"
.RS 4
\h'-04'\(bu\h'+03'The odt output format is undocumented and experimental.
.RE
.RS 4
\h'-04'\(bu\h'+03'See also the
\fIAsciiDoc\fR
distribution BUGS file.
.RE
.SH "AUTHOR"
Written by Stuart Rackham, <srackham@methods.co.nz>
.sp
.SH "RESOURCES"
SourceForge: http://sourceforge.net/projects/asciidoc/
.sp
Main web site: http://www.methods.co.nz/asciidoc/
.sp
.SH "COPYING"
Copyright (C) 2002\-2007 Stuart Rackham. Free use of this software is granted under the terms of the GNU General Public License (GPL).
.sp
.SH "REFERENCES"
.IP " 1." 4
srackham@methods.co.nz
.RS 4
\%mailto:srackham@methods.co.nz
.RE
