.\"     Title: asciidoc
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 09/11/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "ASCIIDOC" "1" "09/11/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
asciidoc \- converts an AsciiDoc text file to DocBook, HTML or LinuxDoc
.SH "SYNOPSIS"
\fIasciidoc\fR [OPTIONS] FILE
.sp
.SH "DESCRIPTION"
The asciidoc(1) command translates the \fIAsciiDoc\fR text file \fIFILE\fR to a DocBook, HTML or LinuxDoc file. If \fIFILE\fR is \fI\-\fR then the standard input is used.
.sp
.SH "OPTIONS"
.PP
\-a, \-\-attribute=ATTRIBUTE
.RS 4
Define or delete document attribute.
\fIATTRIBUTE\fR
is formatted like
\fINAME=VALUE\fR. Command\-line attributes take precedence over document and configuration file attributes. Alternate acceptable forms are
\fINAME\fR
(the
\fIVALUE\fR
defaults to an empty string);
\fINAME!\fR
(delete the
\fINAME\fR
attribute);
\fINAME@\fR
(do not override document or configuration file attributes). Values containing spaces should be enclosed in double\-quote characters. This option may be specified more than once.
.RE
.PP
\-b, \-\-backend=BACKEND
.RS 4
Backend output file format:
\fIdocbook\fR,
\fIxhtml11\fR
or
\fIhtml4\fR. Defaults to
\fIxhtml11\fR.
.RE
.PP
\-f, \-\-conf\-file=CONF_FILE
.RS 4
Use configuration file
\fICONF_FILE\fR.Configuration files processed in command\-line order (after implicit configuration files). This option may be specified more than once.
.RE
.PP
\-d, \-\-doctype=DOCTYPE
.RS 4
Document type:
\fIarticle\fR,
\fImanpage\fR
or
\fIbook\fR. The
\fIbook\fR
document type is only supported by the
\fIdocbook\fR
backend. Default document type is
\fIarticle\fR.
.RE
.PP
\-c, \-\-dump\-conf
.RS 4
Dump configuration to stdout.
.RE
.PP
\-h, \-\-help[=TOPIC]
.RS 4
Print help TOPIC.
\fI\-\-help topics\fR
will print a list of help topics,
\-\-help syntax
summarizes
\fIAsciiDoc\fR
syntax,
\-\-help manpage
prints the
\fIAsciiDoc\fR
manpage.
.RE
.PP
\-e, \-\-no\-conf
.RS 4
Exclude implicitly loaded configuration files except for those named like the input file (\fIinfile.conf\fR
and
\fIinfile\-backend.conf\fR).
.RE
.PP
\-s, \-\-no\-header\-footer
.RS 4
Suppress document header and footer output.
.RE
.PP
\-o, \-\-out\-file=OUT_FILE
.RS 4
Write output to file
\fIOUT_FILE\fR. Defaults to the base name of input file with
\fIbackend\fR
extension. If the input is stdin then the outfile defaults to stdout. If
\fIOUT_FILE\fR
is
\fI\-\fR
then the standard output is used.
.RE
.PP
\-n, \-\-section\-numbers
.RS 4
Auto\-number HTML article section titles. Synonym for
\fI\-a numbered\fR.
.RE
.PP
\-\-unsafe
.RS 4
Disable safe mode. Safe mode is enabled by default, disabling it is potentially dangerous.
.RE
.PP
\-v, \-\-verbose
.RS 4
Verbosely print processing information and configuration file checks to stderr.
.RE
.PP
\-\-version
.RS 4
Print program version number.
.RE
.SH "BUGS"
See the \fIAsciiDoc\fR distribution BUGS file.
.sp
.SH "AUTHOR"
Written by Stuart Rackham, <srackham@methods.co.nz>
.sp
.SH "RESOURCES"
SourceForge: http://sourceforge.net/projects/asciidoc/
.sp
Main web site: http://www.methods.co.nz/asciidoc/
.sp
.SH "COPYING"
Copyright (C) 2002\-2007 Stuart Rackham. Free use of this software is granted under the terms of the GNU General Public License (GPL).
.sp
.SH "REFERENCES"
.IP " 1." 4
srackham@methods.co.nz
.RS 4
\%mailto:srackham@methods.co.nz
.RE
